SAMPLES = ["align_SCN1A", "align_SCN2A", "align_SCN3A", "align_SCN4A", "align_SCN5A", "align_SCN8A"]

rule all:
    input:
        "../../Data/alignments_full_assemb/align_SCN1A/SCN1A.t68d10k45.all.renamed.fa.mafft",
        "../../Data/alignments_full_assemb/align_SCN2A/SCN2A.t68d10k45.all.renamed.fa.mafft",
        "../../Data/alignments_full_assemb/align_SCN3A/SCN3A.t68d10k45.all.renamed.fa.mafft",
        "../../Data/alignments_full_assemb/align_SCN4A/SCN4A.t68d10k45.all.renamed.fa.mafft",
        "../../Data/alignments_full_assemb/align_SCN5A/SCN5A.t68d10k45.all.renamed.fa.mafft",
        "../../Data/alignments_full_assemb/align_SCN8A/SCN8A.t68d10k45.all.renamed.fa.mafft",
        "../../Data/alignments_full_assemb/align_SCN1A/SCN1A.t68d10k45.all.renamed.fa.mafft.noStars",
        "../../Data/alignments_full_assemb/align_SCN2A/SCN2A.t68d10k45.all.renamed.fa.mafft.noStars",
        "../../Data/alignments_full_assemb/align_SCN3A/SCN3A.t68d10k45.all.renamed.fa.mafft.noStars",
        "../../Data/alignments_full_assemb/align_SCN4A/SCN4A.t68d10k45.all.renamed.fa.mafft.noStars",
        "../../Data/alignments_full_assemb/align_SCN5A/SCN5A.t68d10k45.all.renamed.fa.mafft.noStars",
        "../../Data/alignments_full_assemb/align_SCN8A/SCN8A.t68d10k45.all.renamed.fa.mafft.noStars",
        "plot_data/SCN1A.fa",
        "plot_data/SCN2A.fa",
        "plot_data/SCN3A.fa",
        "plot_data/SCN4A.fa",
        "plot_data/SCN5A.fa",
        "plot_data/SCN8A.fa",
        "plot_data/SCN1A.DNA.fa",
        "plot_data/SCN2A.DNA.fa",
        "plot_data/SCN3A.DNA.fa",
        "plot_data/SCN4A.DNA.fa",
        "plot_data/SCN5A.DNA.fa",
        "plot_data/SCN8A.DNA.fa",
        "plot_data/SCN1A.columns",
        "plot_data/SCN3A.columns",
        "plot_data/SCN4A.columns",
        "plot_data/SCN5A.columns",
        "plot_data/SCN8A.columns",
        "plot_data/SCN1A.DNA.trimmed.fa",
        "plot_data/SCN3A.DNA.trimmed.fa",
        "plot_data/SCN4A.DNA.trimmed.fa",
        "plot_data/SCN5A.DNA.trimmed.fa",
        "plot_data/SCN8A.DNA.trimmed.fa",
        "plot_data/SCN1A.DNA.trimmed.fa.raxml.bestTree",
        "plot_data/SCN3A.DNA.trimmed.fa.raxml.bestTree",
        "plot_data/SCN4A.DNA.trimmed.fa.raxml.bestTree",
        "plot_data/SCN5A.DNA.trimmed.fa.raxml.bestTree",
        "plot_data/SCN8A.DNA.trimmed.fa.raxml.bestTree",
        "plot_data/SCN1A.DNA.trimmed.wTree.fa",
        "plot_data/SCN3A.DNA.trimmed.wTree.fa",
        "plot_data/SCN4A.DNA.trimmed.wTree.fa",
        "plot_data/SCN5A.DNA.trimmed.wTree.fa",
        "plot_data/SCN8A.DNA.trimmed.wTree.fa",
        "plot_data/SCN1A.DNA.trimmed.wTree.fa.MEME.json",
        "plot_data/SCN3A.DNA.trimmed.wTree.fa.MEME.json",
        "plot_data/SCN4A.DNA.trimmed.wTree.fa.MEME.json",
        "plot_data/SCN5A.DNA.trimmed.wTree.fa.MEME.json",
        "plot_data/SCN8A.DNA.trimmed.wTree.fa.MEME.json",
        "plot_data/SCN1A.PROT.trimmed.fa",
        "plot_data/SCN3A.PROT.trimmed.fa",
        "plot_data/SCN4A.PROT.trimmed.fa",
        "plot_data/SCN5A.PROT.trimmed.fa",
        "plot_data/SCN8A.PROT.trimmed.fa"

rule run_mafft:
    input:
        "../../Data/alignments_full_assemb/align_{sample}/{sample}.t68d10k45.all.renamed.fa"
    output:
        "../../Data/alignments_full_assemb/align_{sample}/{sample}.t68d10k45.all.renamed.fa.mafft"
    shell:
        "../../scripts/run_mafft.sh {input} -> {output}" 

rule remove_stars:
    input:
        "../../Data/alignments_full_assemb/align_{sample}/{sample}.t68d10k45.all.renamed.fa.mafft"
    output:
        "../../Data/alignments_full_assemb/align_{sample}/{sample}.t68d10k45.all.renamed.fa.mafft.noStars"
    shell:
        "../../scripts/removeStars.sh {input} -> {output}"

rule trim_bad_seqs:
    input:
        "../../Data/alignments_full_assemb/align_{sample}/{sample}.t68d10k45.all.renamed.fa.mafft.noStars"
    output:
        "plot_data/{sample}.fa"
    shell:
        "./trimAl.sh {input} {wildcards.sample}"

rule get_remaining_DNA_seqs:
    input:
        "plot_data/{sample}.fa",
        "../../Data/alignments_full_assemb/align_{sample}/{sample}.t68d10k45.all.renamed.fa.mafft",
        "../../Data/alignments_full_assemb/align_{sample}/{sample}.t68d10k45.DNA.renamed.fa"
    output:
        "plot_data/{sample}.DNA.fa"
    shell:
        "python ../../scripts/getDNAfromProtAlign.py {input} -> {output}"

rule trim_bad_columns:
    input:
        "../../Data/alignments_full_assemb/align_{sample}/{sample}.t68d10k45.all.renamed.fa.mafft.noStars"
    output:
        "plot_data/{sample}.columns"
    shell:
        "./trimAlCol.sh {wildcards.sample} -> {output}"

rule makeDNA:
    input:
        "plot_data/{sample}.columns",
        "plot_data/{sample}.DNA.fa"
    output:
        "plot_data/{sample}.DNA.trimmed.fa"
    shell:
        "python ../../scripts/removeBadCols.py {input} -> {output}"

rule makeTree:
    input:
        "plot_data/{sample}.DNA.trimmed.fa"
    output:
        "plot_data/{sample}.DNA.trimmed.fa.raxml.bestTree"
    shell:
        "../../scripts/make_tree.sh {input}"

rule makeHyphyInput:
    input:
        "plot_data/{sample}.DNA.trimmed.fa",
        "plot_data/{sample}.DNA.trimmed.fa.raxml.bestTree"
    output:
        "plot_data/{sample}.DNA.trimmed.wTree.fa"
    shell:
        "../../scripts/makeHyphyInput.sh {input} {output}" 
        
rule runMeme:
    input:
         "plot_data/{sample}.DNA.trimmed.wTree.fa"
    output:   
         "plot_data/{sample}.DNA.trimmed.wTree.fa.MEME.json"
    shell:
         "hyphy meme {input}"

rule makePROTfromDNA:
    input:
        "plot_data/{sample}.DNA.trimmed.fa"
    output:
        "plot_data/{sample}.PROT.trimmed.fa"
    shell:
        "python ../../scripts/translateDNA.py {input} -> {output}"

